/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1lenguajesformales;

/**
 *
 * @author Mariano
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ingreso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        analizador = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });
        jPanel1.add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 560, 90));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 710, 280));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Resultados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingreso de valores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        analizador.setBackground(new java.awt.Color(0, 204, 204));
        analizador.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        analizador.setForeground(new java.awt.Color(0, 0, 0));
        analizador.setText("Analizar");
        analizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizadorActionPerformed(evt);
            }
        });
        jPanel1.add(analizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 130, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("©Mariano");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoActionPerformed

    private void analizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizadorActionPerformed
        area.setText("");
        int tipoDato=4;
        String queDato;
        String queDatoAnterior;
        String palabra="";
        Clasificador clasificador = new Clasificador(Enum.valueOf(tipoDato));
        String receptorTexto=ingreso.getText();
        String almacenadorLetra;
        for (int i = 0; i < receptorTexto.length(); i++) {
            queDatoAnterior=clasificador.getEnumerador().getEvaluador();
            almacenadorLetra=receptorTexto.substring(i,i+1);
            if(Character.isLetter(receptorTexto.charAt(i))){
                tipoDato=1;
            }else if(almacenadorLetra.equals(".")){
                tipoDato=2;
            }else if(Character.isDigit(receptorTexto.charAt(i))){
                tipoDato=3;
            }else if(almacenadorLetra.equals(" ")){
                tipoDato=5;
            }else if(almacenadorLetra.equals(",")){
                tipoDato=6;
            }else{
                if(almacenadorLetra.equals("(")){
                    i++;
                    almacenadorLetra=receptorTexto.substring(i,i+1);
                    tipoDato=4;
                    if(almacenadorLetra.equals(")")){
                        area.setText(area.getText()+"\nSimbolo: "+"("+almacenadorLetra);
                    }else{
                        area.setText(area.getText()+"\nError "+"("+almacenadorLetra);
                    }
                }else if (almacenadorLetra.equals("[")){
                    i++;
                    almacenadorLetra=receptorTexto.substring(i,i+1);
                    tipoDato=4;
                    if(almacenadorLetra.equals("]")){
                        area.setText(area.getText()+"\nSimbolo: "+"["+almacenadorLetra);
                    }else{
                        area.setText(area.getText()+"\nError "+"["+almacenadorLetra);
                    }
                }else if (almacenadorLetra.equals("{")){
                    i++;
                    almacenadorLetra=receptorTexto.substring(i,i+1);
                    tipoDato=4;
                    if(almacenadorLetra.equals("}")){
                        area.setText(area.getText()+"\nSimbolo: "+"{"+almacenadorLetra);
                    }else{
                        area.setText(area.getText()+"\nError "+"{"+almacenadorLetra);
                    }
                }else if(almacenadorLetra.equals(";")){
                    tipoDato=4;
                    area.setText(area.getText()+"\nSimbolo: "+almacenadorLetra);
                }
            }
            clasificador.setEnumerador(Enum.valueOf(tipoDato));
            queDato= clasificador.getEnumerador().getEvaluador();
            if(queDato.equals("letra")){
                palabra=palabra+almacenadorLetra;
                if(Character.isDigit(palabra.charAt(0))){
                    area.setText(area.getText()+"\nError: "+palabra);
                    palabra="";
                }
            }else if(queDato.equals("punto")){
                if(queDatoAnterior.equals("letra")){
                    area.setText(area.getText()+"\nError: "+palabra+almacenadorLetra);
                    palabra="";
                }else if(queDatoAnterior.equals("numero")){
                    if(palabra.contains(".")){
                        area.setText(area.getText()+"\nError: "+palabra+almacenadorLetra);
                        palabra="";
                    }else if(Character.isLetter(palabra.charAt(0))){
                        area.setText(area.getText()+"\nError: "+palabra+almacenadorLetra);
                        palabra="";
                    }else{
                        palabra=palabra+almacenadorLetra;
                    }           
                }
            }else if(queDato.equals("numero")){
                palabra=palabra+almacenadorLetra;
            }else if(almacenadorLetra.equals(",")||queDato.equals("espacio")){
                if(tipoDato==4){
                    
                }else{
                    if(palabra.equals("")){  
                }else{
                        if(Character.isLetter(palabra.charAt(0))){
                            area.setText(area.getText()+"\nIdentificador: "+palabra);
                            palabra="";
                            tipoDato=4;
                        }else if(Character.isDigit(palabra.charAt(0))){
                            if(palabra.contains(".")){
                                area.setText(area.getText()+"\nDecimal: "+palabra);
                            palabra="";
                            tipoDato=4;
                        }else{
                            area.setText(area.getText()+"\nEntero: "+palabra);
                            palabra="";
                            tipoDato=4;
                        }
                        }    
                }
                }
            }
        }
    }//GEN-LAST:event_analizadorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizador;
    public static javax.swing.JTextArea area;
    private javax.swing.JTextField ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
